"""Deterministic rendering with validation before writes and drift detection."""

from hashlib import sha256
import json
import os
from pathlib import Path
import tempfile
from urllib.parse import quote

import yaml

from .model import Project, check_url
from .rules import ConfigError


HEADER = "# Generated by python -m my_clash build; edit settings/ or the rule lists instead.\n"


def render_ini(project: Project, base_url: str) -> str:
    lines = [HEADER.rstrip(), "[custom]", "", "# First match wins; route order is intentional."]
    for route in project.routes:
        if "file" in route:
            source = f"{base_url}/{quote(route['file'], safe='/')}"
        elif "url" in route:
            source = route["url"]
        else:
            source = "[]" + route["rule"]
        lines.append(f"ruleset={route['target']},{source}")
    lines += ["", "# Proxy groups"]
    for group in project.groups:
        fields = [group["name"], group["type"]]
        fields += ["[]" + choice for choice in group["choices"]]
        if "filter" in group:
            fields.append(group["filter"])
        if group["type"] == "url-test":
            fields += [group["url"], f"{group['interval']},,{group['tolerance']}"]
        lines.append("custom_proxy_group=" + "`".join(fields))
    lines += ["", "enable_rule_generator=true", "overwrite_original_rules=true", ""]
    return "\n".join(lines)


def render(project: Project, base_url: str | None = None) -> dict[str, bytes]:
    base_url = check_url(base_url or project.base_url, base=True)
    output = {"Config/my_config.ini": render_ini(project, base_url).encode("utf-8")}
    output["Config/dns_config.yaml"] = (HEADER + yaml.safe_dump(
        project.dns, allow_unicode=True, sort_keys=False
    )).encode("utf-8")
    catalog = []
    active = {route["file"]: route["target"] for route in project.routes if "file" in route}
    for name, rules in project.rules.items():
        content = (project.root / name).read_bytes()
        output[name] = content
        catalog.append({
            "path": name, "rules": len(rules.rules), "duplicates_removed": rules.duplicates,
            "target": active.get(name), "sha256": sha256(content).hexdigest(),
        })
    output["Config/catalog.json"] = (json.dumps(
        {"summary": project.summary(), "files": catalog}, ensure_ascii=False, indent=2
    ) + "\n").encode("utf-8")
    return output


def _check_output(project: Project, output: Path):
    # Source directories must never be overwritten by generated content.
    protected = [project.root / name for name in ("Ruleset", "BlockAD", "settings", "my_clash", "tests", ".git", ".github", ".venv")]
    for directory in protected:
        if output == directory or output.is_relative_to(directory):
            raise ConfigError(f"输出目录不得位于源文件或内部目录: {output}")


def build(project: Project, output: Path, *, base_url: str | None = None, check: bool = False) -> list[str]:
    files = render(project, base_url)
    output = output.resolve()
    _check_output(project, output)
    paths = []
    for name, content in files.items():
        path = output / name
        if not path.resolve().is_relative_to(output):
            raise ConfigError(f"输出文件越出目标目录: {path}")
        if output != project.root:
            _check_output(project, path.resolve().parent)
        paths.append((name, path, content))
    # Report stale generated lists without deleting anything automatically.
    stale = []
    for directory in ("Ruleset", "BlockAD"):
        for path in (output / directory).rglob("*.list"):
            name = path.relative_to(output).as_posix()
            if name not in files:
                stale.append(name)
    if stale:
        raise ConfigError("发现过期规则产物，请确认后移除或使用新输出目录: " + ", ".join(stale))
    changed = []
    for name, path, content in paths:
        if path.exists() and path.read_bytes() == content:
            continue
        changed.append(name)
        if check:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        descriptor, temporary = tempfile.mkstemp(prefix=".my-clash-", dir=path.parent)
        try:
            with os.fdopen(descriptor, "wb") as stream:
                stream.write(content)
            os.replace(temporary, path)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)
    return changed
